### ISSUE TITLE
Last Inserter ID

### ISSUE THREAD

**Issue by SuperDermo** [trooney/PDODblibBundle#1]
Hi,

I installed the PDODblib Driver and SELECTs are working fine, but when try t oadd new entities I get following error:

SQLSTATE[IM001]: Driver does not support this function: driver does not support lastInsertId()

In our set up FreeTDS with PDO does not support lastInsertId().

How did you solve that problem? Is there any solution for Doctrine2 to make it work? 

Thanks. Tomas.

**Comment by trooney** [comment]
Hey Dermo. This was a quick hack to pull some data. Haven't had time to run the Doctrine2 test suite but will get around to it soon.

**Comment by trooney** [comment]
Someone on SO posted something similar. Will need to work around lastInsertId()

http://stackoverflow.com/questions/6140529/how-can-i-get-the-id-of-the-last-inserted-row-using-pdo-with-sql-server

**Comment by SuperDermo** [comment]
Hi, thanks for the reply. 

I've seen many similar requests - I can work around it for now - actually I don't need the lastInsertedId() right now (just prototyping messaging gateway on MS SQL) and I added the method into the Connection class returning empty string. 

I was more wondering if there is any proper solution which I may have missed or something - some set up ...

**Comment by trooney** [comment]
Added overrides to support transactions and lastInsertId  in 54343ab7d5a77b3939debf0623cca037e2bd69de
