### ISSUE TITLE
About installation

### ISSUE THREAD

**Issue by garciaf** [trooney/PDODblibBundle#2]
Hello 
I would like to use your bundle, but I'm stuck on the installation of this bundle. 
Should I register this bundle in autoload.php ? And in the AppKernel ? If yes how ? 

Otherwise should I add your Bundle in the doctrine bundle. 

Thanks for your help and your time

**Comment by trooney** [comment]
Hey garciaf,

You should know upfront that using this will probably cause you a lot of head ache. Setting it up is a pain and it's probably not best to rely on it for anything other than reading a SQL Server. 

Anyhow, calling this a "bundle" might be misleading. You only need to setup the Doctrine DBAL connection in your Symfony config.yml file. Take a look at the documentation. I've updated it to include a few more setups. I can help you out, but make sure you get your FreeTDS connection working, and a simple PDO connection working before moving on to SF2.

T.

**Comment by garciaf** [comment]
Thanks for your fast reaction and to update the documentation. 

So I check the configuration, and FreeTDS is well configure. Your Bundle work good. I can access to the data base. I had to un-comment 2 return statement to make it work (I supposed it's because I use Symfony 2.0.x) ; 
It works ! 
But to make it works I copied all your source in doctrine-dbal/lib/ folder wich is a pretty hugly way to do it, no ? So I was wondering if there is not a better way to do it. 
If yes how should look like my deps file ? And my autoload.php ? 

Sorry to disturb you once more, I hope my question is not too silly

Thanks again

**Comment by trooney** [comment]
Glad you've got it going! Took me a while to figure it out, so glad someone else could use it. 

What lines did you uncomment? Let me know so I can update the folder. When you say "pretty huge" do you mean the folder structure? It mirrors the Doctrine namespace. It's the best way. As for the deps, I'm just managing that section by hand. Perhaps it should go into the vendor folder later on. Not sure. First time making this kind of thing for Doctrine!

**Comment by garciaf** [comment]
Well, I use the first return for this two functions : 

public function getDatabasePlatform() 

public function getSchemaManager(\Doctrine\DBAL\Connection $conn)

I think it must be related with my version of symfony (2.0.x) 

I guess it would be great to use your bundle in the vendor bundle in an independent way. For now I think I will make a fork of doctrine with your source to make it easier for my team to work with it. 

Thanks for your help and your time...
