### ISSUE TITLE
autoloader.php changed in symfony-standard

### ISSUE THREAD

**Issue by k3wals** [trooney/PDODblibBundle#3]
Hi,

I attempted to install your bundle, but am having some trouble. What directory in vendors do I extract the source of your bundle?

Also, $loader->registerNamespaces method is not recognized when I put it in vendors/autoload.php. There was a recent change to symfony-standard and autoload.php, I'm not sure if it's related.
https://github.com/symfony/symfony-standard/commit/96ed5ba44eac948957824cea029bb4efbbdfc6e9

I'm new to Symfony2, PHP, and OOP in general so I'm not sure how to fix it. Thanks.

**Comment by trooney** [comment]
I'm in the process of migrating to SF2.1 right now, so I'll let you know when I encounter the issue.

**Comment by trooney** [comment]
For SF2.1, I added the following to my composer.json file to get things working:

``` json
{
    "autoload": {
        "psr-0": {
            "PDODblibBundle":"vendor/trooney",
        }
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "trooney/PDODblibBundle",
                "version": "master",
                "source": {
                    "url": "https://github.com/trooney/PDODblibBundle.git",
                    "type": "git",
                    "reference": "master"
                }
            }
        },
    "require": {
        "trooney/PDODblibBundle": "master"
    },
}
```

I recommend taking a look at this package I just discovered: http://packagist.org/packages/isoft/mssql-bundle
