### ISSUE TITLE
Symfony 2.1 install awkward without composer.json

### ISSUE THREAD

**Issue by Bendihossan** [trooney/PDODblibBundle#6]
This project doesn't have a composer.json and is not listed on packagist so installing this bundle with Symfony 2.1 is a little tricky as it requires specify the ZIP as a download which is far from ideal.

Please add a composer.json so that the bundle can be easily installed with Symfony 2.1 :)

**Comment by Kevlys** [comment]
+1 :)

**Comment by somy** [comment]
+1 :)

**Comment by danieleorler** [comment]
+1

**Comment by trooney** [comment]
That only took a year ;)

**Comment by Bendihossan** [comment]
Thanks :)
